plugins {
    id 'java'
    id("io.freefair.lombok") version "8.14"
}

group = 'dev.racel'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation("io.javalin:javalin:6.7.0")
    implementation ('com.corundumstudio.socketio:netty-socketio:2.0.13')

    implementation("org.slf4j:slf4j-api:1.7.25")
    implementation 'org.tinylog:tinylog-api:2.7.0'
    implementation 'org.tinylog:tinylog-impl:2.7.0'
    implementation 'org.tinylog:slf4j-tinylog:2.7.0'

    annotationProcessor("com.fasterxml.jackson.core:jackson-annotations:2.17.2")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.2")
}

test {
    useJUnitPlatform()
}