writer1          = file
writer1.level    = info
writer1.format   = {date} {class-name} {level}: {message}
writer1.file     = log.txt
writer1.charset  = UTF-8
writer1.append   = true
writer1.buffered = true

writer2        = console
writer2.level  = info
writer2.format = {date} {class-name} {level}: {message}
writer2.stream = out